### PR TITLE
Add marginal improvements

### PR DESCRIPTION
**Pull request by zeroed**
While reading the code for another project :yum: I made some minor changes, not particularly important TBH.

### CODE REVIEW

**Comment by zeroed** [comment]
@stefanofontanelli ... may I add `1.9.3-p551` in a `.ruby-version` file?

**Comment by zeroed** [comment]
@stefanofontanelli : A note to [8846ff1](https://github.com/stefanofontanelli/polipus-cassandra/commit/8846ff16be0f55d6260b88b420c985c9b013633b):

IMHO I solved the issue simply encoding to `UTF-8`; the _"other stuff"_ now works...

```
[6] pry(#<Polipus::Storage::CassandraStore>)> obj['headers']
=> "\x04\b{\x15I\"\x12cache-control\x06:\x06EF[\x06I\"\x17no-cache, no-store\x06;\x00FI\"\vpragma\x06;\x00F[\x06I\"\rno-cache\x06;\x00FI\"\x11content-type\x06;\x00F[\x06I\"\x1Dtext/html; charset=UTF-8\x06;\x00FI\"\x15content-language\x06;\x00F[\x06I\"\nen-US\x06;\x00FI\"\fexpires\x06;\x00F[\x06I\"\a-1\x06;\x00FI\"\vserver\x06;\x00F[\x06I\"\x16Microsoft-IIS/7.0\x06;\x00FI\"\bp3p\x06;\x00F[\x06I\"jCP=\"CAO CURa IVAa HISa OUR IND UNI COM NAV INT STA\",policyref=\"http://img.icbdr.com/images/CBP3P.xml\"\x06;\x00FI\"\x15x-aspnet-version\x06;\x00F[\x06I\"\x0E4.0.30319\x06;\x00FI\"\x0Fset-cookie\x06;\x00F[\aI\"jCB%5FSID=404dce41f5d148859242661d62144ee9-488006642-SQ-4; domain=.careerbuilder.com; path=/; HttpOnly\x06;\x00FI\"\x01\xBABID=X100FD888BB525151518687FCE24A000CEEBFA0329A934C2322F974373A4536739901ED4C1C5C2456501E94B1D2070E0FD; domain=.careerbuilder.com; expires=Sun, 19-Jun-2016 09:24:02 GMT; path=/; HttpOnly\x06;\x00FI\"\x11x-powered-by\x06;\x00F[\x06I\"\fASP.NET\x06;\x00FI\"\nx-pby\x06;\x00F[\x06I\"\x0FREBELWEB16\x06;\x00FI\"\tdate\x06;\x00F[\x06I\"\"Fri, 19 Jun 2015 09:24:02 GMT\x06;\x00FI\"\x0Fconnection\x06;\x00F[\x06I\"\nclose\x06;\x00FI\"\x16transfer-encoding\x06;\x00F[\x06I\"\fchunked\x06;\x00FI\"\x15content-encoding\x06;\x00F[\x06I\"\tgzip\x06;\x00FI\"\tvary\x06;\x00F[\x06I\"\x14Accept-encoding\x06;\x00F"

[7] pry(#<Polipus::Storage::CassandraStore>)> obj['headers'].class
=> String

[8] pry(#<Polipus::Storage::CassandraStore>)> obj['headers'].encoding
=> #<Encoding:ASCII-8BIT>

[9] pry(#<Polipus::Storage::CassandraStore>)> MultiJson.encode({"foo" => obj['headers']})
Encoding::UndefinedConversionError: "\xBA" from ASCII-8BIT to UTF-8
from /Users/edoardo/.rvm/gems/ruby-1.9.3-p551/gems/multi_json-1.11.1/lib/multi_json/adapters/json_common.rb:19:in `encode'

[10] pry(#<Polipus::Storage::CassandraStore>)> obj['headers'].to_s.encode('UTF-8', {:invalid => :replace, :undef => :replace, :replace => '?'})
=> "\u0004\b{\u0015I\"\u0012cache-control\u0006:\u0006EF[\u0006I\"\u0017no-cache, no-store\u0006;\u0000FI\"\vpragma\u0006;\u0000F[\u0006I\"\rno-cache\u0006;\u0000FI\"\u0011content-type\u0006;\u0000F[\u0006I\"\u001Dtext/html; charset=UTF-8\u0006;\u0000FI\"\u0015content-language\u0006;\u0000F[\u0006I\"\nen-US\u0006;\u0000FI\"\fexpires\u0006;\u0000F[\u0006I\"\a-1\u0006;\u0000FI\"\vserver\u0006;\u0000F[\u0006I\"\u0016Microsoft-IIS/7.0\u0006;\u0000FI\"\bp3p\u0006;\u0000F[\u0006I\"jCP=\"CAO CURa IVAa HISa OUR IND UNI COM NAV INT STA\",policyref=\"http://img.icbdr.com/images/CBP3P.xml\"\u0006;\u0000FI\"\u0015x-aspnet-version\u0006;\u0000F[\u0006I\"\u000E4.0.30319\u0006;\u0000FI\"\u000Fset-cookie\u0006;\u0000F[\aI\"jCB%5FSID=404dce41f5d148859242661d62144ee9-488006642-SQ-4; domain=.careerbuilder.com; path=/; HttpOnly\u0006;\u0000FI\"\u0001?BID=X100FD888BB525151518687FCE24A000CEEBFA0329A934C2322F974373A4536739901ED4C1C5C2456501E94B1D2070E0FD; domain=.careerbuilder.com; expires=Sun, 19-Jun-2016 09:24:02 GMT; path=/; HttpOnly\u0006;\u0000FI\"\u0011x-powered-by\u0006;\u0000F[\u0006I\"\fASP.NET\u0006;\u0000FI\"\nx-pby\u0006;\u0000F[\u0006I\"\u000FREBELWEB16\u0006;\u0000FI\"\tdate\u0006;\u0000F[\u0006I\"\"Fri, 19 Jun 2015 09:24:02 GMT\u0006;\u0000FI\"\u000Fconnection\u0006;\u0000F[\u0006I\"\nclose\u0006;\u0000FI\"\u0016transfer-encoding\u0006;\u0000F[\u0006I\"\fchunked\u0006;\u0000FI\"\u0015content-encoding\u0006;\u0000F[\u0006I\"\tgzip\u0006;\u0000FI\"\tvary\u0006;\u0000F[\u0006I\"\u0014Accept-encoding\u0006;\u0000F"
```

**Comment by zeroed** [comment]
I think that these changes are becoming _relevant_ and less _marginal_ as the branch name suggest... What you think @stefanofontanelli ?

:yum:

**Comment by stefanofontanelli** [comment]
They seem OK. :+1: if tests are green :)

**Pull request merged**
